service: serverless-api-project

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 10
  memorySize: 512
  versionFunctions: false
  package:
    excludeDevDependencies: true
    exclude:
      - .test/**
  environment:
    ${file(.configs/

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  config: ${self:custom.prefix}-config

functions: ${file(serverless-dynamic.js)}


